### ISSUE TITLE
Boilerpipe fails to extract certain urls with 406 Error

### ISSUE THREAD

**Issue by rshiva** [misja/python-boilerpipe#24]
I'm  trying to extract content for website but boilerpipe fail with this error ..

 File "/local/lib/python2.7/site-packages/boilerpipe/extract/**init**.py", line 36, in **init**
    connection  = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 406: Not Acceptable

First i thought error is coming from urllib2 . So i tried it with urllib2 independently but it was working fine.
These are the few url where its failing ..
http://mlmgod.com/onlinedeals/20-off-on-max-3000-ebay-rs-0-0-other-free-deals-coupons/
http://swapmyapp.com/how-to/use-microsoft-office-for-iphone/
http://www.techeyetech.com/micromax-canvas-tube-specifications-features-price-canvas-tube-palm-theater.html

**Comment by tuxdna** [comment]
@rshiva This seems like an issue outside of `python-boilerpipe`. Can you reproduce this issue now ?

**Comment by thoughts1053** [comment]
I just started using python-boilerpipe on a project and am running into the same issue. Is there no update on this? Thanks.

**Comment by tuxdna** [comment]
@thoughts1053 Can you provide with a sample script that can help replicate this issue?

**Comment by krishnaupadhyay3** [comment]
fixed by [https://github.com/misja/python-boilerpipe/pull/59](#59)
