### ISSUE TITLE
kernel crashes

### ISSUE THREAD

**Issue by mihir-k** [misja/python-boilerpipe#41]
The moment we import Extractor, the python 2.7 kernel crashes.

**Comment by tuxdna** [comment]
@mihir-k You may want to provide more details i.e a set of steps to reproduce your observation will be helpful with details regarding OS, Python version etc.

**Comment by mihir-k** [comment]
@tuxdna 

Python v - 2.7.10 (64-bit)
java v -1.7.0_25 (64-bit)
OS - windows 7 (64-bit)

Crashes on following command
from boilerpipe.extract import Extractor

**Comment by tuxdna** [comment]
@mihir-k I can't reproduce this behavior on a Fedora machine. And I don't have access to Windows OS. You may want to share output of following command 

```
python -v -c "from boilerpipe.extract import Extractor"
```

**Comment by mihir-k** [comment]
I don't know how, but it starts loading now. Thanks for looking into this!
