### ISSUE TITLE
Does anyone use KeepEverythingWithMinKWordsExtractor ?

### ISSUE THREAD

**Issue by hugsbrugs** [misja/python-boilerpipe#42]
Hi and thanks for your work !

Using All extractors works perfectly except with KeepEverythingWithMinKWordsExtractor which seems normal because I believe we should pass and extra argument which would be min keyword length ? Here is the error thrown 

```
Traceback (most recent call last):
  File "python-boilerpipe.py", line 129, in <module>
    main(sys.argv[1:])
  File "python-boilerpipe.py", line 49, in main
    text = extract_text_html(html, extractor, outputtype)
  File "python-boilerpipe.py", line 102, in extract_text_html
    extractor = Extractor(extractor=extractor, html=html)
  File "/usr/local/lib/python2.7/dist-packages/boilerpipe/extract/__init__.py", line 67, in __init__
    "de.l3s.boilerpipe.extractors."+extractor).INSTANCE
AttributeError: type object 'de.l3s.boilerpipe.extractors.KeepEverythingWithMin' has no attribute 'INSTANCE'
```

Does anyone have syntax to launch this extractor ? Thanks !

**Comment by tuxdna** [comment]
@hugsbrugs you are correct, there is an issue with current version. once fixed it should work as in the gist below:

https://gist.github.com/tuxdna/c402217044ddd37003998259a6af0d41

**Comment by tuxdna** [comment]
@hugsbrugs Feel free to checkout the code in this PR https://github.com/misja/python-boilerpipe/pull/43 , and hope it works for you.

If it does, then we can merge it to master.

**Comment by ImpactSeo** [comment]
I'd like to help but I don't know how to test your Pull Request Code on my local machine ... if you have any github guide for this, I'd like to learn !

**Comment by tuxdna** [comment]
@ImpactSeo Thanks for your interest in the project.

For checking out the corresponding code for PR #43 , you can following these steps:

 * Ensure that you have `git`, `python`, and `virtualenv` setup on your machine.
 * Clone the code from `git@github.com:tuxdna/python-boilerpipe.git` and checkout branch named `issues_42`

```
git clone git@github.com:tuxdna/python-boilerpipe.git
cd python-boilerpipe
git checkout issues_42
```

Now install python-boilerpipe from that branch as mentioned in README: https://github.com/tuxdna/python-boilerpipe/tree/issues_42#installation

```
virtualenv env
source env/bin/activate
pip install -r requirements.txt
python setup.py install
```

Then you can verify if the new changes work for you using this script:

  * https://gist.github.com/tuxdna/c402217044ddd37003998259a6af0d41

I hope that helps.

**Comment by tuxdna** [comment]
Closed via https://github.com/misja/python-boilerpipe/pull/43
