### ISSUE TITLE
getImages no longer works 

### ISSUE THREAD

**Issue by md3sum** [misja/python-boilerpipe#5]
@misja :
The boilerpipe library 1.2.0 no longer has the ImageExtractor class [de.l3s.boilerpipe.sax.ImageExtractor]
It might be worth removing this feature or commenting it out for now (even though I know you have not included it in the documentation in the Readme.rst).

If you know of another way to retrieve it using python-boilerpipe, I'd be happy to hear because I would like the images. 

Cheers

**Comment by Ninjakannon** [comment]
Even when using a version of boilerpipe-1.2.0.jar built from the most recent source, and therefore including the ImageExtractor class, I received an error calling `getImages()`. I forked the repository and fixed the error. A [pull request](https://github.com/misja/python-boilerpipe/pull/31) is pending, but for now my fork is here: https://github.com/Ninjakannon/python-boilerpipe.
