### ISSUE TITLE
Fix simple typo: argment -> argument

### ISSUE THREAD

**Issue by timgates42** [misja/python-boilerpipe#58]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine README.md.
2. Search for `argment`.

# Expected Behaviour

1. Should read `argument`.

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/python-boilerpipe/pull/new/bugfix_typo_argument

Thanks.

**Comment by tuxdna** [comment]
Closed via - https://github.com/misja/python-boilerpipe/commit/37a4037278fda8ca21d85a96eb0c988be0f093e1
